version: "2"

linters:
  enable:
    - bodyclose
    - contextcheck
    # - depguard
    - durationcheck
    - dupl
    - errchkjson
    - errname
    - exhaustive
    - copyloopvar  # Go 1.24+ has enhanced loop variable semantics, but this linter still helps catch issues
    - gocritic
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - revive
    # - rowserrcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    # - wastedassign
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
