name: Continuous Integration
on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: sudo apt-get update
      - run: sudo apt-get install pass gnome-keyring dbus-x11
      - run: go test -race ./...
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: brew install pass gnupg
      - run: go test -race ./...
